# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui_pub2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 700))
        MainWindow.setMaximumSize(QtCore.QSize(400, 700))
        MainWindow.setBaseSize(QtCore.QSize(320, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/custom1/svg_original/down-arrow (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.97)
        MainWindow.setStyleSheet("*{background-color: rgb(226, 226, 226);\n"
"    font-size: 13px;}\n"
"\n"
"/*------------------------------------------------------------QToolTip*/\n"
"QToolTip {\n"
"    color: rgb(230, 230, 230);\n"
"    background-color: rgb(153, 153, 153);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity:20;\n"
"}\n"
"\n"
"\n"
"\n"
"/*--------------------------------------------------------------QScrolBar*/\n"
"    /* ---------------------------VERTICAL ----------------------*/\n"
"    /*Загальна форма*/\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(211, 211, 211);\n"
"    width: 15px;\n"
"    margin: 15px 0px 15px 0px;\n"
"    padding: 0px 3px 0px 3px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"    /* HANDLE BAR VERTICAL*/\n"
"QScrollBar::handle:vertical {    \n"
"    background-color:rgb(153, 153, 149);\n"
"    min-height: 30px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(246, 191, 39);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(220, 180, 41);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(211, 211, 211);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(184, 184, 180);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(153, 153, 149);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(211, 211, 211);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(184, 184, 180);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(153, 153, 149);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical{\n"
"    image: url(:/custom1/icons_custom/au.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin-right: 2px;\n"
"    margin-top:1px;\n"
"    margin-left:2px;\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical{\n"
"    image: url(:/custom1/icons_custom/ad.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin-right: 2px;\n"
"    margin-bottom:1px;\n"
"    margin-left:2px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"    /* ---------------------------HORIZONTAL ----------------------*/\n"
"    /*Загальна форма*/\n"
" QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(211, 211, 211);\n"
"    height: 15px;\n"
"    margin: 0px 15px 0px 15px;\n"
"    padding: 3px 0px 3px 0px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"    /* HANDLE BAR HORIZONTAL*/\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color:rgb(153, 153, 149);\n"
"    min-width: 30px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(246, 191, 39);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(220, 180, 41);\n"
"}\n"
"\n"
"/* BTN LEFT - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(211, 211, 211);\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(184, 184, 180);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(153, 153, 149);\n"
"}\n"
"\n"
"/* BTN RIGHT - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(211, 211, 211);\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(184, 184, 180);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(153, 153, 149);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal{\n"
"    image: url(:/custom1/icons_custom/al.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin-bottom: 2px;\n"
"    margin-top:2px;\n"
"    margin-left:1px;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal{\n"
"    image: url(:/custom1/icons_custom/ar.svg);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    margin-right: 1px;\n"
"    margin-bottom:2px;\n"
"    margin-top:2px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"QGroupBox {\n"
"    font: bold;\n"
"    border: 1px solid silver;\n"
"    border-radius: 6px;\n"
"    margin-top: 0px;\n"
"    background-color: rgb(184, 184, 184);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 7px;\n"
"    top: 0px;\n"
"    padding: 10px 0px 0px 0px;\n"
"}\n"
"\n"
"QLabel{background-color: rgb(184, 184, 184);}\n"
"\n"
"QCheckBox{background-color: rgb(184, 184, 184);}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/custom1/icons_custom/switch_disable.svg);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/custom1/icons_custom/switch_enable.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 38px;\n"
"    height: 19px;\n"
"}\n"
"\n"
"\n"
"\n"
"QRadioButton{\n"
"    background-color: rgb(184, 184, 184);\n"
"    margin-left: 10px;\n"
"}\n"
"\n"
"QGroupBox::indicator {\n"
"    width: 44px;\n"
"    height: 22px;\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked {\n"
"    image: url(:/custom1/icons_custom/switch_disable.svg);\n"
"}\n"
"QGroupBox::indicator:checked {\n"
"    image: url(:/custom1/icons_custom/switch_enable.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 17px;\n"
"    height: 17px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    image: url(:/custom1/icons_custom/rb_enable.svg);\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    image: url(:/custom1/icons_custom/rb_disable.svg);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    background-color:  rgb(165, 165, 165);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(155, 155, 155);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(246, 191, 39);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("12")
        #font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: rgb(246, 191, 39);\n"
"    font: 14px bold;\n"
"    padding: 5px;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{background-color: rgb(226, 226, 226);}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
#        font.setPointSize(1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{background-color: rgb(226, 226, 226);}\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayout_5.addWidget(self.frame)
        self.gb_import = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_import.setStyleSheet("QLabel{margin-left:10px;}")
        self.gb_import.setObjectName("gb_import")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_import)
        self.verticalLayout_2.setContentsMargins(-1, 35, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.l_cur_file = QtWidgets.QLabel(self.gb_import)
        self.l_cur_file.setMinimumSize(QtCore.QSize(0, 48))
        self.l_cur_file.setStyleSheet("")
        self.l_cur_file.setObjectName("l_cur_file")
        self.verticalLayout_8.addWidget(self.l_cur_file)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.b_import = QtWidgets.QPushButton(self.gb_import)
        self.b_import.setMinimumSize(QtCore.QSize(50, 50))
        self.b_import.setMaximumSize(QtCore.QSize(50, 50))
        self.b_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_import.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/custom1/icons_custom/ad.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_import.setIcon(icon1)
        self.b_import.setIconSize(QtCore.QSize(24, 24))
        self.b_import.setObjectName("b_import")
        self.horizontalLayout_3.addWidget(self.b_import)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.gb_import)
        self.gb_word = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_word.setEnabled(False)
        self.gb_word.setObjectName("gb_word")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_word)
        self.verticalLayout_3.setContentsMargins(-1, 35, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_det_years = QtWidgets.QCheckBox(self.gb_word)
        self.cb_det_years.setObjectName("cb_det_years")
        self.verticalLayout_6.addWidget(self.cb_det_years)
        self.cb_det_types = QtWidgets.QCheckBox(self.gb_word)
        self.cb_det_types.setObjectName("cb_det_types")
        self.verticalLayout_6.addWidget(self.cb_det_types)
        self.cb_det_tab = QtWidgets.QCheckBox(self.gb_word)
        self.cb_det_tab.setObjectName("cb_det_tab")
        self.verticalLayout_6.addWidget(self.cb_det_tab)
        self.line_2 = QtWidgets.QFrame(self.gb_word)
        self.line_2.setEnabled(False)
        self.line_2.setMaximumSize(QtCore.QSize(265, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.rb_sublist_off = QtWidgets.QRadioButton(self.gb_word)
        self.rb_sublist_off.setChecked(True)
        self.rb_sublist_off.setObjectName("rb_sublist_off")
        self.verticalLayout_6.addWidget(self.rb_sublist_off)
        self.rb_sublist_text = QtWidgets.QRadioButton(self.gb_word)
        self.rb_sublist_text.setObjectName("rb_sublist_text")
        self.verticalLayout_6.addWidget(self.rb_sublist_text)
        self.rb_sublist_table = QtWidgets.QRadioButton(self.gb_word)
        self.rb_sublist_table.setObjectName("rb_sublist_table")
        self.verticalLayout_6.addWidget(self.rb_sublist_table)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.b_word = QtWidgets.QPushButton(self.gb_word)
        self.b_word.setMinimumSize(QtCore.QSize(50, 50))
        self.b_word.setMaximumSize(QtCore.QSize(50, 50))
        self.b_word.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_word.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/black/svg_original/docx-file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_word.setIcon(icon2)
        self.b_word.setIconSize(QtCore.QSize(36, 36))
        self.b_word.setObjectName("b_word")
        self.horizontalLayout.addWidget(self.b_word)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.gb_word)
        self.gb_excel = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_excel.setEnabled(False)
        self.gb_excel.setObjectName("gb_excel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_excel)
        self.verticalLayout_4.setContentsMargins(-1, 35, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cb_float_format = QtWidgets.QCheckBox(self.gb_excel)
        self.cb_float_format.setObjectName("cb_float_format")
        self.verticalLayout_7.addWidget(self.cb_float_format)
        self.cb_add_profi_col = QtWidgets.QCheckBox(self.gb_excel)
        self.cb_add_profi_col.setObjectName("cb_add_profi_col")
        self.verticalLayout_7.addWidget(self.cb_add_profi_col)
        self.line = QtWidgets.QFrame(self.gb_excel)
        self.line.setMaximumSize(QtCore.QSize(265, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.rb_excel_com = QtWidgets.QRadioButton(self.gb_excel)
        self.rb_excel_com.setBaseSize(QtCore.QSize(60, 250))
        self.rb_excel_com.setChecked(True)
        self.rb_excel_com.setObjectName("rb_excel_com")
        self.verticalLayout_7.addWidget(self.rb_excel_com)
        self.rb_excel_sep = QtWidgets.QRadioButton(self.gb_excel)
        self.rb_excel_sep.setObjectName("rb_excel_sep")
        self.verticalLayout_7.addWidget(self.rb_excel_sep)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.b_excel = QtWidgets.QPushButton(self.gb_excel)
        self.b_excel.setMinimumSize(QtCore.QSize(50, 50))
        self.b_excel.setMaximumSize(QtCore.QSize(50, 50))
        self.b_excel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_excel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/black/svg_original/excel (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_excel.setIcon(icon3)
        self.b_excel.setIconSize(QtCore.QSize(36, 36))
        self.b_excel.setObjectName("b_excel")
        self.horizontalLayout_2.addWidget(self.b_excel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.gb_excel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skarb"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">конвертер відомостей ДРФО (доходи ФО)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Обробка та аналіз експортованих таблиць доходів реєстру ДРФО. Придатні до опрацювання файли формату *.XML (файли формату PDF не підтримуються). Власноручне внесення змін до файлу або збереження формату сторонніми програмами може призвести до помилок конвертування. </span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/OlehOleinikov/Skarb\"><span style=\" text-decoration: underline; color:#0000ff;\">GitHub project page</span></a></p></body></html>"))
        self.gb_import.setTitle(_translate("MainWindow", "Обрати файл (*.XML):"))
        self.l_cur_file.setText(_translate("MainWindow", "Статус: Готовий до роботи\n"
""))
        self.gb_word.setTitle(_translate("MainWindow", "Звіт Word (*.docx):"))
        self.cb_det_years.setText(_translate("MainWindow", "Деталізувати по роках"))
        self.cb_det_types.setText(_translate("MainWindow", "Деталізувати по видам доходу"))
        self.cb_det_tab.setText(_translate("MainWindow", "Додати основну таблицю"))
        self.rb_sublist_off.setText(_translate("MainWindow", "Не розгортати пункти"))
        self.rb_sublist_text.setText(_translate("MainWindow", "Підпункти списком"))
        self.rb_sublist_table.setText(_translate("MainWindow", "Підпункти таблицями"))
        self.gb_excel.setTitle(_translate("MainWindow", "Зберегти Excel (*.xlsx)"))
        self.cb_float_format.setText(_translate("MainWindow", "Формат сум (12890,00 -> 12 890.00)"))
        self.cb_add_profi_col.setText(_translate("MainWindow", "Колонка прибутку (= дохід - податок)"))
        self.rb_excel_com.setText(_translate("MainWindow", "всі записи в одному файлі"))
        self.rb_excel_sep.setText(_translate("MainWindow", "окремий файл щодо кожної особи"))
import gui.res_icons
